In [ ]:
!pip install langdetect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 14.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=305ba75c372c51de83c21bfa2f7d368afcd0b0960e51b003ba8faa8cb78dc74b
  Stored in directory: /root/.cache/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

In [ ]:
import pandas as pd

df = pd.read_csv('/content/youtube_reviews_2025_all.csv')
df.head()

,review_id,user_name,userImage,review_description,rating,thumbs_up,reviewCreatedVersion,review_date,developer_response,developer_response_date,appVersion,review_date.1,month,year,source
0,f61485f4-e3e3-409b-b152-fd95f6039289,Kimberlie Pagán,https://play-lh.googleusercontent.com/a-/ALV-U...,ever since yall took away the block button for...,1,1,20.51.39,2025-12-31 23:59:14,NaN,NaN,20.51.39,2025-12-31 23:59:14,12,2025,Google Play
1,cfb78be2-e5ab-4b68-a127-a24333626e5a,MD Mahide Hassan,https://play-lh.googleusercontent.com/a/ACg8oc...,Nice,5,0,20.49.44,2025-12-31 23:58:33,NaN,NaN,20.49.44,2025-12-31 23:58:33,12,2025,Google Play
2,c8a98639-231b-4f62-9cb2-eca28a09c57c,Sunday Nwolisa,https://play-lh.googleusercontent.com/a/ACg8oc...,A nice app,5,0,10.18.55,2025-12-31 23:54:39,NaN,NaN,10.18.55,2025-12-31 23:54:39,12,2025,Google Play
3,4f2a89d3-a1ca-4bdc-8c94-2bb7a77d8ac0,Ramki Ramki,https://play-lh.googleusercontent.com/a/ACg8oc...,ஃபைவ்,1,0,20.51.39,2025-12-31 23:52:30,NaN,NaN,20.51.39,2025-12-31 23:52:30,12,2025,Google Play
4,fea42746-01d2-4a81-97cc-9d62f32e45a5,Steve Seetahal,https://play-lh.googleusercontent.com/a-/ALV-U...,"2 minor bugs observed , with this update 1 bac...",2,0,20.51.39,2025-12-31 23:50:17,NaN,NaN,20.51.39,2025-12-31 23:50:17,12,2025,Google Play

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1058464 entries, 0 to 1058463
Data columns (total 15 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   review_id                1058464 non-null  object
 1   user_name                1058459 non-null  object
 2   userImage                1058464 non-null  object
 3   review_description       1058429 non-null  object
 4   rating                   1058464 non-null  int64
 5   thumbs_up                1058464 non-null  int64
 6   reviewCreatedVersion     1034916 non-null  object
 7   review_date              1058464 non-null  object
 8   developer_response       0 non-null        float64
 9   developer_response_date  0 non-null        float64
 10  appVersion               1034916 non-null  object
 11  review_date.1            1058464 non-null  object
 12  month                    1058464 non-null  int64
 13  year                     1058464 non-null  int64
 14  source                   1058464 non-null  object
dtypes: float64(2), int64(4), object(9)
memory usage: 121.1+ MB

**Collect English Dataset**

In [ ]:
from langdetect import detect, DetectorFactory
DetectorFactory.seed = 0

def is_english(text):
    try:
        return detect(text) == 'en'
    except:
        return False

df = df.dropna(subset=['review_description'])
df_en = df[df['review_description'].apply(is_english)]

print("Jumlah data Inggris:", len(df_en))

Jumlah data Inggris: 437236

In [ ]:
df_en

,review_id,user_name,userImage,review_description,rating,thumbs_up,reviewCreatedVersion,review_date,developer_response,developer_response_date,appVersion,review_date.1,month,year,source
0,f61485f4-e3e3-409b-b152-fd95f6039289,Kimberlie Pagán,https://play-lh.googleusercontent.com/a-/ALV-U...,ever since yall took away the block button for...,1,1,20.51.39,2025-12-31 23:59:14,NaN,NaN,20.51.39,2025-12-31 23:59:14,12,2025,Google Play
4,fea42746-01d2-4a81-97cc-9d62f32e45a5,Steve Seetahal,https://play-lh.googleusercontent.com/a-/ALV-U...,"2 minor bugs observed , with this update 1 bac...",2,0,20.51.39,2025-12-31 23:50:17,NaN,NaN,20.51.39,2025-12-31 23:50:17,12,2025,Google Play
5,180ffb72-db7b-4f56-a000-2d95a9e5a12c,Keisha Gwarega,https://play-lh.googleusercontent.com/a/ACg8oc...,To search for cartoons and movies,5,0,11.04.56,2025-12-31 23:49:26,NaN,NaN,11.04.56,2025-12-31 23:49:26,12,2025,Google Play
6,ae9f9095-9a39-4087-95e9-44bc904ec78a,Napoleon Joaquin,https://play-lh.googleusercontent.com/a/ACg8oc...,Just I update my phone and YouTube is Not avai...,1,0,13.30.56,2025-12-31 23:48:21,NaN,NaN,13.30.56,2025-12-31 23:48:21,12,2025,Google Play
11,73da9d25-838e-4e1b-935e-d832dc4b085a,Al-imam,https://play-lh.googleusercontent.com/a-/ALV-U...,"New playlist system is awkward and hard, i use...",1,0,20.51.39,2025-12-31 23:40:18,NaN,NaN,20.51.39,2025-12-31 23:40:18,12,2025,Google Play
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1058456,d183fdc7-8d47-4065-ab8c-9de92696723c,Odeh Esther,https://play-lh.googleusercontent.com/a/ACg8oc...,It was good An great,5,0,NaN,2025-01-01 00:10:38,NaN,NaN,NaN,2025-01-01 00:10:38,1,2025,Google Play
1058458,b692e5ef-7a18-4b59-a87e-ad0ae1c9860e,D M,https://play-lh.googleusercontent.com/a/ACg8oc...,Can't disable YT Shorts on Android. Fix it.,1,0,19.50.40,2025-01-01 00:08:52,NaN,NaN,19.50.40,2025-01-01 00:08:52,1,2025,Google Play
1058459,7e400d15-3301-420c-9295-2fab9bf410a8,Drazen Bjelovuk,https://play-lh.googleusercontent.com/a-/ALV-U...,"As with most Google apps, settings/options are...",1,7,19.50.40,2025-01-01 00:08:12,NaN,NaN,19.50.40,2025-01-01 00:08:12,1,2025,Google Play
1058460,2bcd54d3-1f89-4dac-857b-476be2dcefec,Agbetrobou Oliviare,https://play-lh.googleusercontent.com/a/ACg8oc...,YouTube Oliver,5,0,10.49.59,2025-01-01 00:07:50,NaN,NaN,10.49.59,2025-01-01 00:07:50,1,2025,Google Play
1058462,19148b96-24f9-4cb3-b43d-79b2b5030227,Steven E,https://play-lh.googleusercontent.com/a/ACg8oc...,Bloatware,1,0,NaN,2025-01-01 00:05:18,NaN,NaN,NaN,2025-01-01 00:05:18,1,2025,Google Play

In [ ]:
df_en.to_csv('youtube_reviews_english_2025.csv', index=False)
print("CSV berhasil disimpan.")

CSV berhasil disimpan.

**Filter Reviews with Minimum length 20 & Collect 500 data each Month**

In [ ]:
# Filter review terlalu pendek (misal <20 karakter)
MIN_REVIEW_LENGTH = 20
df_minLength = df_en[df_en['review_description'].str.len() >= MIN_REVIEW_LENGTH]

# Sampling 500 review per bulan
SAMPLE_PER_MONTH = 500

df_sample = (
    df_minLength.groupby('month', group_keys=False)
      .apply(lambda x: x.sample(
          n=min(SAMPLE_PER_MONTH, len(x)),
          random_state=42
      ))
)

df_sample.reset_index(drop=True, inplace=True)

# Cek distribusi per bulan
print(df_sample['month'].value_counts().sort_index())

month
1     500
2     500
3     500
4     500
5     500
6     500
7     500
8     500
9     500
10    500
11    500
12    500
Name: count, dtype: int64

/tmp/ipython-input-2075365186.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(

In [ ]:
df_sample

,review_id,user_name,userImage,review_description,rating,thumbs_up,reviewCreatedVersion,review_date,developer_response,developer_response_date,appVersion,review_date.1,month,year,source
0,29b06b39-ef79-4f1f-aeb7-17456fcdc646,Ashish Bista,https://play-lh.googleusercontent.com/a-/ALV-U...,"This app is trash, it pops up a ad every 5 sec...",1,0,19.50.42,2025-01-17 07:47:38,NaN,NaN,19.50.42,2025-01-17 07:47:38,1,2025,Google Play
1,c21b7039-9df9-4270-9a97-bb742a1e648d,Harshit Singh,https://play-lh.googleusercontent.com/a-/ALV-U...,New update is worst all videos are showing so ...,2,1,19.50.40,2025-01-08 16:24:55,NaN,NaN,19.50.40,2025-01-08 16:24:55,1,2025,Google Play
2,6816f08d-8122-4e35-98f7-e6d7a4d883bb,Debojit Hazarika,https://play-lh.googleusercontent.com/a/ACg8oc...,Everything nice but add was irretating,5,0,19.50.40,2025-01-02 12:58:38,NaN,NaN,19.50.40,2025-01-02 12:58:38,1,2025,Google Play
3,b70ebdbb-17bb-4bd4-afe9-a12c4338b851,Mini Vasanthakumar,https://play-lh.googleusercontent.com/a/ACg8oc...,I love it but o i hate the $3X side plus some ...,4,0,19.50.40,2025-01-06 10:41:17,NaN,NaN,19.50.40,2025-01-06 10:41:17,1,2025,Google Play
4,d9aeadda-bcd4-4e0d-9556-a1cadee646f7,Nadine Mukiri,https://play-lh.googleusercontent.com/a/ACg8oc...,First of all it's YouTube ads no biggie but we...,2,3,18.38.37,2025-01-05 20:59:26,NaN,NaN,18.38.37,2025-01-05 20:59:26,1,2025,Google Play
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,6c692fcb-0f46-42c8-af97-ecf61ceaa932,Mohammad Hasan,https://play-lh.googleusercontent.com/a/ACg8oc...,Mujhe bhut Pasnd hai,5,0,20.47.46,2025-12-04 09:44:50,NaN,NaN,20.47.46,2025-12-04 09:44:50,12,2025,Google Play
5996,b7a99f04-fc14-47bb-a5a4-89176399d445,Ilya Orlenko,https://play-lh.googleusercontent.com/a-/ALV-U...,Make auto-translate on/off switch,1,1,20.47.46,2025-12-09 10:50:08,NaN,NaN,20.47.46,2025-12-09 10:50:08,12,2025,Google Play
5997,c1bac59b-f91a-45ed-9613-8042e4560fa7,vaibhav sapkal,https://play-lh.googleusercontent.com/a/ACg8oc...,Youtub is changing life,5,0,20.07.39,2025-12-12 08:08:09,NaN,NaN,20.07.39,2025-12-12 08:08:09,12,2025,Google Play
5998,9760091f-683f-4948-8cd8-0f19ee7961ad,Ahmed Khan,https://play-lh.googleusercontent.com/a/ACg8oc...,👌 cool thanks for your service and sacrifice a...,5,0,12.43.52,2025-12-30 23:36:33,NaN,NaN,12.43.52,2025-12-30 23:36:33,12,2025,Google Play
5999,d46c73b4-4a54-4ec6-bd6d-e137bae9b413,Retroid_Pocket_Five,https://play-lh.googleusercontent.com/a-/ALV-U...,Now has too many annoying advertising and the ...,2,0,20.51.39,2025-12-29 21:04:28,NaN,NaN,20.51.39,2025-12-29 21:04:28,12,2025,Google Play

In [ ]:
df_sample.to_csv('youtube_reviews_sampleenglish_2025.csv', index=False)
print("youtube_reviews_english_2025.csv berhasil disimpan.")

youtube_reviews_english_2025.csv berhasil disimpan.